Time::DATE_FORMATS[:feed] = "%B %d, %Y - %H:%M"
Time::DATE_FORMATS[:full_human] = "%B %d, %Y - %l:%M %p"
Time::DATE_FORMATS[:datetime] = "%FT%T%:z"
Time::DATE_FORMATS[:date] = "%B %e, %Y"
Time::DATE_FORMATS[:stats] = "%Y/%m/%d %H:%M:%S"